language: node_js
node_js:
- "10"
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn install
script:
- yarn bt
